# Dockerfile2
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# Accept dynamic argument
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

# Set environment variable
ENV ENVIRONMENT=development

COPY . .

CMD ["node", "app.js"]